src/main/java/com/treasure_data/client/Constants.java, src/main/java/com/treasure_data/client/HttpConnectionImpl.java, src/test/java/com/treasure_data/client/TestHttpConnectionImpl.java
Use system property "http.proxyUser" and "http.proxyPassword" for proxy
authentication that requires password. Bear in mind that Java's
HttpURLConnection honors "http.proxyHost" and "http.proxyPort" but it
does not use "http.proxyUser" and "http.proxyPassword".
=> Proxy Password Authentication

src/main/java/com/treasure_data/client/DefaultClientAdaptorImpl.java, src/main/java/com/treasure_data/model/Job.java, src/test/java/com/treasure_data/client/TestSubmitJob.java
This pull request is to add `pool_name` field when submitting jobs to Treasure Data, based on 0.5.x branch.
=> add accessor for pool_name to submit jobs into specified resource pool

README.md, src/main/java/com/treasuredata/client/TDClient.java, src/main/java/com/treasuredata/client/TDClientBuilder.java, src/main/java/com/treasuredata/client/TDClientConfig.java, src/main/java/com/treasuredata/client/TDHttpClient.java, src/test/java/com/treasuredata/client/TestProxyAccess.java, src/test/java/com/treasuredata/client/TestSSLProxyAccess.java, src/test/java/com/treasuredata/client/TestServerFailures.java, src/test/java/com/treasuredata/client/TestTDClient.java, src/test/java/com/treasuredata/client/TestTDClientConfig.java, src/test/java/com/treasuredata/client/TestTDHttpClient.java
- Removed TDConfig builder, instead added `TDClient.newBuilder()`. 
- It makes easy to remember the start point of configuring TDClient.
- It also reduces the code size related to TDClientConfig
- Using public final field for TDClientConfig and ProxyConfig object.
=> Configuring TDClient with TDClientBuilder

src/main/java/com/treasuredata/client/TDClient.java, src/main/java/com/treasuredata/client/model/TDQuery.java, src/test/java/com/treasuredata/client/builder/TestTDClientBuilder.java
This is necessary so that classes in another package can call setXxx methods.
=> TDClientBuilder needs to be public

src/main/java/com/treasuredata/client/TDClient.java, src/main/java/com/treasuredata/client/TDClientApi.java, src/main/java/com/treasuredata/client/model/TDExportFileFormatType.java, src/main/java/com/treasuredata/client/model/TDExportJobRequest.java, src/main/java/com/treasuredata/client/model/TDJob.java, src/test/java/com/treasuredata/client/TestTDClient.java
This pull-request adds TDClient.submitExportJob method.
TDExportJobRequest.toString doesn't output secretAccessKey for better security.
I used Date class for `from` and `to` fields so that users don't get confused about unit (seconds or milliseconds).
=> Adding support for export jobs

src/main/java/com/treasuredata/client/AbstractTDClientBuilder.java, src/main/java/com/treasuredata/client/TDClientConfig.java, src/test/java/com/treasuredata/client/TestTDClientConfig.java
For convenience of implementing td-jdbc, which only can pass Properties object.
=> Use enum for TDClientConfig keys

src/main/java/com/treasuredata/client/TDClient.java, src/main/java/com/treasuredata/client/model/TDJobRequest.java, src/main/java/com/treasuredata/client/model/TDJobRequestBuilder.java, src/test/java/com/treasuredata/client/TestTDClient.java
Also deprecate public `TdJobRequest` constructor as it makes it impractical to add fields to `TdJobRequest` without making breaking changes (i.e. adding arguments to the public constructor).
Preferred way of instantiating a `TdJobRequest` should be through the builder.
=> add scheduled_time param

src/main/java/com/treasuredata/client/TDClient.java, src/main/java/com/treasuredata/client/model/TDBulkLoadSessionStartRequest.java, src/main/java/com/treasuredata/client/model/TDBulkLoadSessionStartRequestBuilder.java, src/test/java/com/treasuredata/client/TestTDClient.java, src/test/java/com/treasuredata/client/model/TDBulkLoadSessionStartRequestTest.java
The `scheduled_time` field must be a string.
=> fix bulk load start with scheduled time

src/main/java/com/treasuredata/client/TDClient.java, src/main/java/com/treasuredata/client/TDClientHttpConflictException.java, src/main/java/com/treasuredata/client/TDHttpClient.java, src/main/java/com/treasuredata/client/model/TDApiErrorMessage.java, src/main/java/com/treasuredata/client/model/TDJobRequest.java, src/main/java/com/treasuredata/client/model/TDJobRequestBuilder.java, src/test/java/com/treasuredata/client/TestTDClient.java
The domain_key can be used to make job submission idempotent and retryable. The domain_key must be unique across a TD account. The TD rest api returns 409 for job submissions with a domain_key that has already been used.
=> add support for job domain keys

pom.xml
For using td-client with scala, we cannot use jackson 2.6.2 because of a class binding bug:
https://github.com/FasterXML/jackson-module-scala
At least we need to use 2.6.5 or higher
=> Upgrade jackson to 2.6.7

src/main/java/com/treasuredata/client/model/TDJob.java
My program uses td-client and needs to change the behavior of depending on query types like presto, hive. To do that, it's better to add a type field to TDJob model.
=> Add type property to TDJob model class

src/main/java/com/treasuredata/client/TDHttpClient.java, src/test/java/com/treasuredata/client/TestTDClient.java
This allows the client to transparently support other authorization methods such as [JWT](https://jwt.io/) as well as future TD-specific `Authorization` header values.
=> allow setting arbitrary Authorization header

src/main/java/com/treasuredata/client/TDHttpClient.java
Jetty HttpClient starts some threads. Having explicit names makes it
easy to debug thread-related issues. Default name is `HttpClient`
(actual thread name becomes longer because Jetty adds more
such as `HttpClient@159413332-12-selector-...`).
=> Set thread names to HTTP client threads

pom.xml
Found unpackString bug in msgpack-core https://github.com/msgpack/msgpack-java/pull/387.  But td-client-java never uses unpackString, so this upgrade is only for future safety.
=> Upgrade to msgpack-java 0.8.10

src/main/java/com/treasuredata/client/AbstractTDClientBuilder.java, src/main/java/com/treasuredata/client/TDClientConfig.java, src/main/java/com/treasuredata/client/TDHttpClient.java, src/test/java/com/treasuredata/client/TestServerFailures.java
My application was waiting for td-client and the control didn't return from td-client. It looks like a jetty client v9.2 bug because it was waiting to get a connection from the connection pool. But, just in case, it's better to customize a request timeout as one of td-client parameters.
The following is a part of my application thread dump:
```
"main" prio=10 tid=0x00007f51d0011000 nid=0x5460 waiting on condition [0x00007f51d8d1b000]
java.lang.Thread.State: WAITING (parking)
at sun.misc.Unsafe.park(Native Method)
- parking to wait for  <0x00000007ba9c2388> (a java.util.concurrent.CountDownLatch$Sync)
at java.util.concurrent.locks.LockSupport.park(LockSupport.java:186)
at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:834)
at …
```
=> Configure request timeout

src/main/java/com/treasuredata/client/TDHttpClient.java, src/test/java/com/treasuredata/client/TestTDClient.java
Supposedly some old apikeys do not have a `account-id/` prefix.
=> restore support for old apikeys

pom.xml, src/main/java/com/treasuredata/client/TDClientHttpConflictException.java, src/main/java/com/treasuredata/client/TDClientHttpException.java, src/main/java/com/treasuredata/client/TDClientHttpNotFoundException.java, src/main/java/com/treasuredata/client/TDClientHttpTooManyRequestsException.java, src/main/java/com/treasuredata/client/TDClientHttpUnauthorizedException.java, src/main/java/com/treasuredata/client/TDHttpClient.java, src/test/java/com/treasuredata/client/TestTDHttpClient.java
The TD API returns 429 with a `Retry-After` header when rate limiting requests.
Respect the `Retry-After` value when retrying and also propagate the the value to the user in a new `TDClientHttpTooManyRequestsException` when the configured retry has been exceeded.
=> Handle 429 Too Many Requests

src/main/java/com/treasuredata/client/TDClient.java, src/main/java/com/treasuredata/client/TDHttpClient.java, src/main/java/com/treasuredata/client/model/JsonCollectionRootName.java, src/main/java/com/treasuredata/client/model/TDBulkImportSession.java, src/main/java/com/treasuredata/client/model/TDDatabase.java, src/main/java/com/treasuredata/client/model/TDSavedQuery.java
This is followup of #81. At an extension of this library could have {{@JsonRootName}} for non list field. To prevent possible name conflict on {{@JsonRootName}}, it would be safe to use separate annotation for list field.
=> Avoid possible annotation name conflict

src/main/java/com/treasuredata/client/TDClient.java, src/main/java/com/treasuredata/client/TDClientApi.java, src/main/java/com/treasuredata/client/model/TDConnectionLookupResult.java, src/main/java/com/treasuredata/client/model/TDJobRequest.java, src/main/java/com/treasuredata/client/model/TDJobRequestBuilder.java, src/test/java/com/treasuredata/client/TestTDClient.java
A new release of API supports result_connection_id and
result_connection_settings when issuing a job. There is another REST API
to lookup connection id by name.
=> Add support for result_connection_id and result_connection_settings

.gitignore, CHANGES.txt, README.md, checkstyle-suppressions.xml, circle.yml, pom.xml, src/main/java/com/treasuredata/client/AbstractTDClientBuilder.java, src/main/java/com/treasuredata/client/ExponentialBackOff.java, src/main/java/com/treasuredata/client/HttpStatus.java, src/main/java/com/treasuredata/client/TDApiRequest.java, src/main/java/com/treasuredata/client/TDClient.java, src/main/java/com/treasuredata/client/TDClientConfig.java, src/main/java/com/treasuredata/client/TDClientHttpConflictException.java, src/main/java/com/treasuredata/client/TDClientHttpNotFoundException.java, src/main/java/com/treasuredata/client/TDClientProcessingException.java, src/main/java/com/treasuredata/client/TDHttpClient.java, src/main/java/com/treasuredata/client/TDHttpMethod.java, src/main/java/com/treasuredata/client/TDHttpRequestHandler.java, src/main/java/com/treasuredata/client/TDHttpRequestHandlers.java, src/main/java/com/treasuredata/client/TDRequestErrorHandler.java, src/main/java/com/treasuredata/client/impl/ProxyAuthenticator.java, src/test/java/com/treasuredata/client/TDRequestErrorHandlerTest.java, src/test/java/com/treasuredata/client/TestProxyAccess.java, src/test/java/com/treasuredata/client/TestSSLProxyAccess.java, src/test/java/com/treasuredata/client/TestServerFailures.java, src/test/java/com/treasuredata/client/TestTDClient.java, src/test/java/com/treasuredata/client/TestTDClientConfig.java, src/test/java/com/treasuredata/client/TestTDHttpClient.java
- When td-client is used with jetty 9.4.4, it causes severe problems (especially when using Presto 0.187 + td-client at the same time). 
- Fixing various issues in #99 (jetty upgrade) seems difficult
- This PR also includes Guava, Jackson upgrades
- Targeting Java8 because Guava 21.0 or higher basically requires Java8.
=> Use OkHttp 

src/main/java/com/treasuredata/client/TDHttpClient.java
A subclass of TDHttpClient needs to override withHeaders method to
return an instance of the subclass. The new instance shares all private
fields excepting headers (config, httpClient, and objectMapper) with the
old instance. But because the fields are private, constructor of the
subclass can't call super with the private objects.
This change lets the subclass to overrie withHeaders method as
following:
return new MyTDHttpClient(super.withHeaders(headers));
=> Let subclass of TDHttpClient call super to initialize from TDHttpClient

src/main/java/com/treasuredata/client/TDClient.java, src/main/java/com/treasuredata/client/TDClientApi.java
Allow having the resource pool name parameter for performing bulk import, keep the backward compatibility.
=> Add resource pool name in performing bulk import

src/main/java/com/treasuredata/client/TDClient.java, src/main/java/com/treasuredata/client/TDClientApi.java, src/main/java/com/treasuredata/client/model/TDExportResultJobRequest.java, src/test/java/com/treasuredata/client/TestTDClient.java
- This PR enables to access result_export endpoint (`POST /v3/job/result_export/:id`).
- This endpoint access is already supported in [td-client-ruby](https://github.com/treasure-data/td-client-ruby/blob/614a463551f9ac91fb13f1c845f21720a5f7569c/lib/td/client/api/export.rb#L25-L36)
```java
TDClient client = TDClient
.newBuilder()
.setApiKey("api_key")
.build();
TDExportResultJobRequest jobRequest = TDExportResultJobRequest.builder()
.jobId("12345")
.result("td://@/my_db/my_table")
.build();
String jobId = client.submitResultExportJob(jobRequest);
System.out.println(jobId); // => 12346
```
=> Support result_export on TDClient

src/main/java/com/treasuredata/client/TDClient.java, src/main/java/com/treasuredata/client/model/TDExportResultJobRequest.java, src/test/java/com/treasuredata/client/TestTDClient.java
- This PR add new parameters `resultConnectionId` (ID String) and `resultConnectionSettings` (JSON String)
- These parameters are used to specify the connector where the job result is exported to, instead of `resultOutput`(legacy url)
```java
TDClient client = TDClient
.newBuilder()
.setApiKey("apikey")
.build();
TDExportResultJobRequest jobRequest = TDExportResultJobRequest.builder()
.jobId("17")
.resultConnectionId("3822")
.resultConnectionSettings(
"{\"api_key\":\"api_key\"," +
"\"user_database_name\":\"sample_database\"," +
"\"user_table_name\":\"sample_output_table\"}")
.build();
client.submitResultExportJob(jobRequest)
```
=> Add new parameters for TDExportResultJobRequest

src/main/java/com/treasuredata/client/model/TDJob.java, src/test/java/com/treasuredata/client/TestTDClient.java
- This PR add `num_record` property at `TDJob`
- `num_record` property is an item contained in TD api endpoint response, and current version of `TDJob` does not map this property.
- In digdag, I want to set `num_record` of last td job into params, and use like this
```yml
+task1:
td_run> saved_query
+task2:
sh>: task_that_needs_num_record.sh ${td.last_job_num_record}
```
=> Support `num_record` attribute at `TDJob`

src/main/java/com/treasuredata/client/model/TDExportResultJobRequest.java, src/main/java/com/treasuredata/client/model/TDJob.java
- This PR is followup for #113 #114
- Fix checkstyle violation ( executed by `mvn validate` )
- I noticed that `mvn validate` ends with `SUCCESS` now in my local environment.
```sh
$  mvn validate            
[INFO] Scanning for projects...
[INFO] 
[INFO] -----------------< com.treasuredata.client:td-client >------------------
[INFO] Building Treasure Data Client for Java 0.8.5
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-enforcer-plugin:1.2:enforce (enforce-maven) @ td-client ---
[INFO] 
[INFO] --- maven-dependency-versions-check-plugin:2.0.2:check (default) @ td-client ---
[INFO] Checking dependency versions
[INFO] 
[INFO] --- maven-checkstyle-plugin:2.17:check (default) @ td-client ---
[INFO] Starting audit...
Audit done. …
```
=> Fix coding style

.circleci/config.yml, pom.xml
Jackson 2.8 has an security issue. We need to upgrade it to 2.8.11(.1) https://github.com/treasure-data/td-client-java/network/alert/pom.xml/com.fasterxml.jackson.core:jackson-databind/open
And also fixed the CircleCI issue by disabling JVM fork.
=> Upgrade jackson for addressing the security issue

pom.xml, src/main/java/com/treasuredata/client/TDClient.java, src/main/java/com/treasuredata/client/TDClientApi.java, src/main/java/com/treasuredata/client/TDClientConfig.java, src/main/java/com/treasuredata/client/TDHttpClient.java, src/main/java/com/treasuredata/client/TDRequestErrorHandler.java, src/test/java/com/treasuredata/client/TestTDClient.java
- It's normal that table distribution data can be missing, so it should return Optional.
- Suppress 404 (not found) warning message, because it can frequently happen.
=> Return optional value for tableDistribution

src/main/java/com/treasuredata/client/TDClient.java, src/test/java/com/treasuredata/client/TestTDClient.java
Hi folks,
I want to get listJobs with ranges such as 100 overs. But listJobs with from_to parameter method doesn't works(only 20 lists are callbacks). I suppose that `td-java-api` has not right parameter with `/v3/job/list`  because `td-ruby-api` is using `from/to`, Not ` from_id/to_id`.
- td-ruby-api 
https://github.com/treasure-data/td-client-ruby/blob/d296734c1b2f79bae595fa4c1249c18bcb8c05a7/lib/td/client/api/job.rb#L13
- td-java-api 
https://github.com/treasure-data/td-client-java/blob/2ce2d1346233f82949d9047138bb48a017ff4f2a/src/main/java/com/treasuredata/client/TDClient.java#L647
Here is the evidence, please check it!
- Results of fixed codes.
Thanks,
=> Fix listJobs with from_to method

src/main/java/com/treasuredata/client/TDClient.java, src/main/java/com/treasuredata/client/model/TDJob.java, src/main/java/com/treasuredata/client/model/TDJobRequest.java, src/main/java/com/treasuredata/client/model/TDJobRequestBuilder.java, src/main/java/com/treasuredata/client/model/TDSaveQueryRequest.java, src/main/java/com/treasuredata/client/model/TDSavedQuery.java, src/main/java/com/treasuredata/client/model/TDSavedQueryBuilder.java, src/main/java/com/treasuredata/client/model/TDSavedQueryUpdateRequest.java, src/main/java/com/treasuredata/client/model/TDSavedQueryUpdateRequestBuilder.java, src/test/java/com/treasuredata/client/TestTDClient.java
I would like to introduce **engine_version** parameter to Hive,Presto experimentally.
Currently _EXPERIMENTAL_, _STABLE_, _LEGACY_, _CURRENT_ are pre-defined as engine version. But limited versions are avilable. It depends on Engine.
=> Introduce engine version in Hive, Presto

pom.xml
Fix security issue by upgrading checkstyle to 8.18, see: https://nvd.nist.gov/vuln/detail/CVE-2019-9658
=> CVE-2019-9658 Fix security issue

src/main/java/com/treasuredata/client/TDClient.java, src/main/java/com/treasuredata/client/TDClientApi.java, src/main/java/com/treasuredata/client/model/TDApiKey.java, src/test/java/com/treasuredata/client/TestTDClient.java
Add support to API key validation endpoint, it allows to validate and collect information about the API key currently used.
=> Add support to API key validation endpoint

src/main/java/com/treasuredata/client/TDClient.java, src/main/java/com/treasuredata/client/TDClientApi.java, src/test/java/com/treasuredata/client/TestTDClient.java
Idempotent key enables us to retry create table request idempotently. We can update td-client to support this kind of request experimentally.
=> Support idempotent key in createTable

pom.xml
This PR relocates Guava 21.0 in all-in-one jar generated by maven-shade-plugin to avoid class loading issues. several Java libraries depends on different versions of Guava.
=> Shade/relocate Guava for all-in-one jar by maven-shade-plugin

CHANGES.txt, pom.xml
Jackson 2.9.x is compatible the version used in Spark, msgpack-java, etc.
We should upgrade it to 2.9.x 
- Some customers might suffer from dependency issue, so we should bump the minor version of td-client-java from 0.8 to 0.9
=> CLT-1449: Upgrade jackson to 2.9.x

findbugs-exclude-filter.xml, pom.xml
See CVE for details: https://nvd.nist.gov/vuln/detail/CVE-2018-10237
=> CVE-2018-10237 Upgrade Guava version

README.md
* fix maven URL 501
```
501 HTTPS Required. 
Use https://repo1.maven.org/maven2/
More information at https://links.sonatype.com/central/501-https-required
```
=> Update maven url

pom.xml
3.12.0 -> 3.12.10 is an API compatible upgrade. 
- Several bugs that caused connection leak and crash are fixed https://square.github.io/okhttp/changelog_3x/#version-3126, https://square.github.io/okhttp/changelog_3x/#version-3122
=> Upgrade okhttp to 3.12.10

pom.xml, src/main/java/com/treasuredata/client/TDHttpClient.java
- Use the latest version of okhttp 3.x series, which supports HTTP2. Although td-client-java doesn't need to use HTTP2, the other components that use td-client-java can use HTTP2 with okhttp with this upgrade. 
- okhttp 4.x requires Kotlin, so sticking to 3.x series is better to avoid unnecessary dependencies.
- For applications sensitive to okhttp dependencies, the shade version td-client-shade.jar hides okhttp3 and okio packages.
=> Upgrade to okhttp 3.14.7

CHANGES.txt, pom.xml, src/main/java/com/treasure_data/client/HttpConnectionImpl.java
The old version `v0.2.14.3` is using HTTP to request to API endpoint. HTTP is unsecure and should be replaced by HTTPS.
The PR only updates the scheme from HTTP to HTTPS and should not impact to current stable version.
=> Use https scheme to request to API endpoint

pom.xml
PR will bring the new profile that disable strict javadoc lint check for Java 8.
=> Fix errors when generating javadoc

src/main/java/com/treasuredata/client/TDHttpClient.java, src/test/java/com/treasuredata/client/TestTDHttpClient.java
`TDHttpClient` sets the value of `getClientName()` to User-Agent header and if we specify User-Agent header by `withHeader()`, multiple User-Agent headers are sent to the server. 
This pull request fixes the behavior to combine them to a single User-Agent header.
=> Avoid User-Agent header duplication

src/main/java/com/treasuredata/client/TDRequestErrorHandler.java, src/test/java/com/treasuredata/client/TestTDClient.java
Until okhttp 4.1.0.rc, it could raise okhttp3.internal.http2.StreamResetException when endpoint is busy for other requests. 
We should retry on this error, as it's a temporal unavailable.
=> Add retry pattern for StreamResetException

src/main/java/com/treasuredata/client/TDClientApi.java
We plan to deprecate /v3/user/apikey/validate endpoint.
Instead of removing the code, I request to add deprecated annotation.
=> Deprecate validateAPIKey

src/main/java/com/treasuredata/client/TDClient.java, src/main/java/com/treasuredata/client/model/TDColumn.java
**Context:** The expected column order to use in append schema API is: `column name, column type, column SQL alias`. Because the existing attributes in `TDColumn` class are sometimes confusing:
* `name` is column SQL alias.
* `key` is column name.
That led the append schema API uses the wrong attribute, it should use `key` as a column name instead of `name` as a SQL alias. The PR brings the small patch to fix that issue. We might want to update the attributes in `TDColumn` to make it more obvious though.
=> Fix the column order in append schema API

src/test/java/com/treasuredata/client/TestTDClient.java
Follow-up https://github.com/treasure-data/td-client-java/pull/164, because API key validation has been removed completely, thus its related test cases should be removed too.
=> Remove API Key validation test cases because it has been deprecated.

src/main/java/com/treasuredata/client/model/TDBulkImportSession.java, src/test/java/com/treasuredata/client/TestProxyAccess.java
- TD http endpoints got disabled since Mar 1.
https://docs.treasuredata.com/display/public/PD/March+2021+Release+Note#March2021ReleaseNote-EndofLifeforHTTPEndpoints
- JDK makes Basic authentication for HTTPS tunneling disabled by default in JDK 8u111 or higher.
https://www.oracle.com/java/technologies/javase/8u111-relnotes.html
To pass the test for authentication for HTTPS tunneling, we need to set `disabledSchemes` jvm property.
=> Drop the test code for http endpoint

src/main/java/com/treasuredata/client/TDClientException.java, src/main/java/com/treasuredata/client/TDRequestErrorHandler.java, src/test/java/com/treasuredata/client/TestServerFailures.java
When a server returns non success(200) error, the error handler expects a JSON serialized body which contains error details. But reading the error body could also raise an `IOException` and we wrap it as `INVALID_JSON_RESPONSE`.
As one of `IOException`, when `SocketTimeoutException` occurs, wrapping it as `INVALID_JSON_RESPONSE` would hide the timeout. Actually http status has already received, error details is useful for logging/auditing but might not be required. For example, 
* At 404 but timeout at reading error body : NOT_FOUND handler should process it even with the timeout 
* At 500 but timeout at reading error body : Retry handler should process it even with the timeout
=> Handle timeout at error body read

pom.xml, src/main/java/com/treasuredata/client/TDHttpClient.java, src/main/java/com/treasuredata/client/model/ObjectMappers.java, src/main/java/com/treasuredata/client/model/TDSavedQueryUpdateRequest.java
Guava 31.1 has not been updated for a year since 2022. Using the latest version will reduce the chance of dependency hell. 
And also, jackson binding for Guava is no longer necessary as we have removed Guava Optional usage thanks to @exoego in #181
=> Upgrade Guava 31.1 and remove jackson-guava binding

.circleci/config.yml
See https://circleci.com/developer/ja/orbs/orb/circleci/maven
- `curcleci/maven` orb is now used. It handles maven caching with less code.
- CircleCI config is bumped to `2.1`. This is required to use the CirlceCI orb. Otherwise `maven/with_cache` command is not recognized.
With cache hit | Without cache hit 
---|---
6s | 13s
Not so impressive enhancements 😅
=> CI: Cache Maven deps to speed up test job

src/main/java/com/treasuredata/client/TDHttpRequestHandler.java, src/main/java/com/treasuredata/client/TDHttpRequestHandlers.java
This allows `TDHttpRequestHandler` in lambda notation for many use-cases.
=> Make TDHttpRequestHandler FunctionalInterface

src/main/java/com/treasuredata/client/TDApiRequest.java, src/main/java/com/treasuredata/client/TDClient.java, src/main/java/com/treasuredata/client/TDClientException.java, src/main/java/com/treasuredata/client/TDHttpClient.java, src/main/java/com/treasuredata/client/model/TDColumn.java, src/main/java/com/treasuredata/client/model/TDUserList.java
=> Replace Guava checkNotNull with JDK requireNonNull

src/main/java/com/treasuredata/client/TDApiRequest.java, src/main/java/com/treasuredata/client/TDClient.java, src/main/java/com/treasuredata/client/model/TDQuery.java, src/test/java/com/treasuredata/client/Example.java, src/test/java/com/treasuredata/client/TestTDClient.java
Part of #135
https://github.com/google/guava/wiki/Why-we-deprecated-Throwables.propagate
> In many cases, you'll be able to use throw e or throw new RuntimeException(e) with no change in behavior. This sometimes lets you remove other code.
=> Inline Guava Throwables.propagate

src/test/java/com/treasuredata/client/TestTDHttpClient.java
=> Fix flaky test: Set a error margin to make test robust

src/main/java/com/treasuredata/client/model/TDColumn.java, src/main/java/com/treasuredata/client/model/TDDatabase.java, src/main/java/com/treasuredata/client/model/TDTable.java, src/main/java/com/treasuredata/client/model/TDTableDistribution.java
=> Replace Guava's Objects util with JDK's equivalents

pom.xml, src/test/java/com/treasuredata/client/TDRequestErrorHandlerTest.java, src/test/java/com/treasuredata/client/TestTDHttpClient.java
JDK 8 introduced Date-and-Time, inspired by joda-time.
We no longer need joda-time for testing.
=> testdep: Replace joda-time with JDK8 equivalents

.github/release-drafter.yml, .github/workflows/release-drafter.yml
- Introduce release-drafter github action to generate release note automatically when tagging a commit.
----
> Release Drafter / update_release_draft (pull_request) 
https://github.com/treasure-data/td-client-java/actions/runs/4022500542/jobs/6912305907
The above job keeps failing until this pull request is merged into master. So, we can ignore failures for this job.
=> Introduce release-drafter github action

src/test/java/com/treasuredata/client/TestProxyAccess.java, src/test/java/com/treasuredata/client/TestSSLProxyAccess.java
This is an issue found while working in #232.
Assertion in `finally` block is generally a not good idea.
Because it hides the real exception thrown in `try` block and makes debugging hard.
```java
try {
doSomething();   // unexpected exception thrown
assertThat(...);
} finally {
assertThat(...); // AssertionError is thrown, which hides the exception thrown from try block
}
```
=> Avoid assertion in finally block

src/test/java/com/treasuredata/client/TDRequestErrorHandlerTest.java, src/test/java/com/treasuredata/client/TestServerFailures.java, src/test/java/com/treasuredata/client/TestTDClient.java, src/test/java/com/treasuredata/client/TestTDClientConfig.java, src/test/java/com/treasuredata/client/TestTDHttpClient.java, src/test/java/com/treasuredata/client/model/TDBulkLoadSessionStartRequestTest.java, src/test/java/com/treasuredata/client/model/TDUserTest.java
This makes it easy to migrate to JUnit 5 and remove deprecated codes.
=> Avoid trivial deprecations in test codes

README.md, src/main/java/com/treasuredata/client/model/TDQuery.java, src/test/java/com/treasuredata/client/Example.java, src/test/java/com/treasuredata/client/TestProxyAccess.java, src/test/java/com/treasuredata/client/TestTDClient.java, src/test/java/com/treasuredata/client/model/TestTDColumn.java
try-with-resource is highly encouraged since it ensure resource closing with simpler code
=> Encourage try-with-resource

src/main/java/com/treasuredata/client/TDClient.java, src/main/java/com/treasuredata/client/TDHttpClient.java, src/main/java/com/treasuredata/client/TDRequestErrorHandler.java, src/main/java/com/treasuredata/client/UrlPathSegmentEscaper.java, src/main/java/com/treasuredata/client/impl/ProxyAuthenticator.java, src/test/java/com/treasuredata/client/TestServerFailures.java, src/test/java/com/treasuredata/client/TestTDHttpClient.java, src/test/java/com/treasuredata/client/TestUrlEscaper.java, src/test/java/com/treasuredata/client/TestUrlPathSegmentEscaper.java
Part of #135 
- HTTP Header constants are all inlined.
- `UrlPathSegmentEscaper` class is added. This class is compatible with `com.google.common.net.UrlEscapers.urlPathSegmentEscaper`.
=> Replace Guava net module with JDK equivalents

pom.xml, src/test/java/com/treasuredata/client/TestProxyAccess.java, src/test/java/com/treasuredata/client/TestSSLProxyAccess.java
- Before: https://github.com/adamfisk/LittleProxy it appears to be no longer actively developed. Last release: 2017 Mar.
- After: https://github.com/LittleProxy/LittleProxy A community-based fork. Last release: 2022 Oct.
=> testlib: Bump littleproxy

pom.xml, src/main/java/com/treasuredata/client/TDClient.java, src/main/java/com/treasuredata/client/model/TDColumn.java, src/test/java/com/treasuredata/client/TestTDClient.java
No reason to use two different JSON library?
=> Replace JSON.simple with already-inuse Jackson

src/main/java/com/treasuredata/client/AbstractTDClientBuilder.java, src/main/java/com/treasuredata/client/TDApiRequest.java, src/main/java/com/treasuredata/client/TDClient.java, src/main/java/com/treasuredata/client/TDClientApi.java, src/main/java/com/treasuredata/client/TDClientConfig.java, src/main/java/com/treasuredata/client/TDHttpClient.java, src/main/java/com/treasuredata/client/TDHttpRequestHandlers.java, src/main/java/com/treasuredata/client/model/TDApiErrorMessage.java, src/main/java/com/treasuredata/client/model/TDColumnType.java, src/main/java/com/treasuredata/client/model/impl/TDScheduleRunResult.java, src/test/java/com/treasuredata/client/Example.java, src/test/java/com/treasuredata/client/TestTDClient.java, src/test/java/com/treasuredata/client/TestTDClientConfig.java, src/test/java/com/treasuredata/client/TestTDHttpClient.java, src/test/java/com/treasuredata/client/model/TestTDColumn.java
Part of #135 
This is the final Guava deprecation and removal.
After this PR and a new minor version cut, I think we could delete the deprecated one and guava dependency.
The problem is `Multimap<K, V>`. How should we remove it?
Possible directions:
1. Just replace it with `Map<K, Collection<V>>` and introduce breaking change aggressively. 
2. Add new overloads with `Map<K, Col<V>>` and deprecate the old methods with `Muiltimap`.
- In this direction, some classes require new members to avoid conflict with `TDClientConfig#headers` and `TDApiRequest#getHeaderParams()`. See new members `~V2`. 
I propose picking 2nd since it helps users to migrate.
WDYT?
=> Deprecate Guava Multimap and Function in favor of JDK & Remove Guava collections

pom.xml
- Delete `javax.annotation-api` from dependency libraries
- Update `org.immutables:*` to `2.10.1`
- Fix configurations in maven-javadoc-plugin
- Upgrade checkstyle to v9
=> Clean up dependency libraries and etc / Improve pom.xml

src/main/java/com/treasuredata/client/model/TDDatabase.java
Ad `user_id` and `description` to the response
=> Update response for database api

src/main/java/com/treasuredata/client/model/TDSavedQuery.java
Add `executing_user_id` and `description` to the response
=> Update response for schedule list

src/main/java/com/treasuredata/client/model/TDTable.java, src/test/java/com/treasuredata/client/TestTDClient.java
Add `user id` and `description` to the response
=> Update response for table list

pom.xml
The compile scope dependencies are missing from the released POM since 0.9.7. e.g. https://repo1.maven.org/maven2/com/treasuredata/client/td-client/0.9.7/td-client-0.9.7.pom
This was caused by the maven-shade-plugin update in #192. Previously, maven-shade-plugin did not create the dependency reduced POM when [shadedArtifactAttached](https://maven.apache.org/plugins/maven-shade-plugin/shade-mojo.html#shadedArtifactAttached) was enabled, but in 3.3.0 the behavior changes and the plugin creates the dependency reduced POM regardless of the shadedArtifactAttached setting ([MSHADE-321](https://issues.apache.org/jira/browse/MSHADE-321)).
The problem is that the plugin not only creates the dependency reduced POM but also [modifies the current project model to use the generated …
=> Fix missing compile scope dependencies in released POM

src/main/java/com/treasuredata/client/model/TDTable.java, src/test/java/com/treasuredata/client/TestTDClient.java
Reverts treasure-data/td-client-java#352
=> Revert "Update response for table list"

src/main/java/com/treasuredata/client/model/TDDatabase.java
Reverts treasure-data/td-client-java#350
=> Revert "Update response for database api"

src/main/java/com/treasuredata/client/TDRequestErrorHandler.java, src/test/java/com/treasuredata/client/TDRequestErrorHandlerTest.java
Make "Connection reset" and "Broken pipe" SocketException retryable. Previously these exceptions would cause immediate failure.
=> Retry requests on "Connection reset" and "Broken pipe" SocketException
