treasure-data/td-client-java

src/main/java/com/treasure_data/client/DefaultClientAdaptorImpl.java
Do not retry if proxy authentication is failed.
=> Do not retry on 407 (Proxy Authentication Required) error

README.md
=> Fix duplicated line on Readme

src/main/java/com/treasuredata/client/TDClient.java, src/main/java/com/treasuredata/client/model/TDJobRequest.java, src/main/java/com/treasuredata/client/model/TDJobRequestBuilder.java, src/test/java/com/treasuredata/client/TestTDClient.java
Added a field to post `pool_name` field when users submit jobs to Treasure Data API.
=> add pool_name optional field to submit jobs

.gitignore, README.md, pom.xml, src/main/java/com/treasuredata/client/model/TDJob.java, src/test/java/com/treasuredata/client/Example.java, src/test/resources/logback-test.xml
Create td-client-(version)-shade.jar package for solving #20
=> Rename jetty package

src/main/java/com/treasuredata/client/TDApiRequest.java, src/main/java/com/treasuredata/client/TDClient.java, src/main/java/com/treasuredata/client/TDHttpClient.java, src/main/java/com/treasuredata/client/model/TDJob.java, src/main/java/com/treasuredata/client/model/TDJobRequest.java, src/main/java/com/treasuredata/client/model/TDJobRequestBuilder.java, src/test/java/com/treasuredata/client/TestTDClient.java
This pull-request adds very primitive support for bulkload jobs.
This is only for issuing a job. So it doesn't include guess, preview, or scheduling. But I think this should be the first change because this includes some internal changes.
=> Add support for bulkload jobs

src/main/java/com/treasuredata/client/TDClient.java
getVersion was always returning "unknown"
=> Fix resource path to pom.properties

src/main/java/com/treasuredata/client/TDClient.java, src/main/java/com/treasuredata/client/TDClientApi.java, src/main/java/com/treasuredata/client/model/impl/TDScheduleRunResult.java, src/test/java/com/treasuredata/client/TestTDClient.java
This method is used to run a saved query. Date argument is used to
control the return value of TD_SCHEDULED_TIME().
=> Add submitSchedule API

src/main/java/com/treasuredata/client/TDClient.java, src/main/java/com/treasuredata/client/model/TDJobRequest.java, src/main/java/com/treasuredata/client/model/TDJobRequestBuilder.java, src/test/java/com/treasuredata/client/TestTDClient.java
Reverts treasure-data/td-client-java#38. We need to wait the next TD API update.
=> `Revert "add scheduled_time param"

src/test/java/com/treasuredata/client/TestTDClient.java
This feature is now available in the TD rest api.
=> enable submitJobWithScheduledTime test

pom.xml, src/main/java/com/treasuredata/client/TDClient.java, src/main/java/com/treasuredata/client/TDClientApi.java, src/main/java/com/treasuredata/client/model/StringToNumberSerializer.java, src/main/java/com/treasuredata/client/model/TDUser.java, src/test/java/com/treasuredata/client/TestTDClient.java, src/test/java/com/treasuredata/client/model/TDUserTest.java
=> add method to get current user

src/main/java/com/treasuredata/client/TDClientConfig.java
s/ybi.jp-east.idcfcloud.com/api.ybi.idcfcloud.com/
=> Update YBI endpoint in comment

src/main/java/com/treasuredata/client/AbstractTDClientBuilder.java, src/main/java/com/treasuredata/client/TDClientBuilder.java
Make setters return TDClientBuilder instead of AbstractTDClientBuilder.
=> fix TDClientBuilder setter return types

pom.xml
Let's upgrade msgpack-core to v0.8.8.
=> Upgrade to msgpack-core v0.8.8

src/main/java/com/treasuredata/client/TDClientException.java, src/main/java/com/treasuredata/client/TDClientSSLException.java, src/main/java/com/treasuredata/client/TDHttpClient.java
A possible fix of #62. Here is JavaDoc of SSLException: https://docs.oracle.com/javase/8/docs/api/javax/net/ssl/SSLException.html
=> Handle SSLException and retry if it is uncategorized or protocol error

pom.xml, src/main/java/com/treasuredata/client/AbstractTDClientBuilder.java, src/main/java/com/treasuredata/client/TDClient.java, src/main/java/com/treasuredata/client/TDClientApi.java, src/main/java/com/treasuredata/client/TDClientConfig.java, src/main/java/com/treasuredata/client/model/TDExportJobRequest.java, src/main/java/com/treasuredata/client/model/TDSavedQueryStartRequest.java, src/test/java/com/treasuredata/client/TestTDClient.java
Note: this requires the next version of the TD api to be released. Currently works in dev.
=> export and saved query domain key support

src/main/java/com/treasuredata/client/TDApiRequest.java, src/main/java/com/treasuredata/client/TDHttpClient.java
* make redirect following configurable
* make request success classification customizable to allow handlers to consider e.g. 302 to be successful
=> make redirect following configurable

src/main/java/com/treasuredata/client/TDClient.java, src/main/java/com/treasuredata/client/TDClientApi.java, src/test/java/com/treasuredata/client/TestTDClient.java
~~Note: This requires the release of a new version the the TD rest api.~~
This is now good to go.
=> add domain key support to partial delete request

src/main/java/com/treasuredata/client/model/TDExportFileFormatType.java
=> json-line.gz is wrong, line-json.gz is correct

src/main/java/com/treasuredata/client/TDClient.java, src/main/java/com/treasuredata/client/TDClientApi.java, src/test/java/com/treasuredata/client/TestTDClient.java
This PR adds `TDClient#showTable`.
=> Add TDClient#showTable

CHANGES.txt, pom.xml
This PR prepares 0.7.37 release.
=> release 0.7.37

src/main/java/com/treasuredata/client/TDClient.java, src/main/java/com/treasuredata/client/TDClientApi.java
This PR adds `TDClient#appendTableSchema`.
=> Add TDClient#appendTableSchema

CHANGES.txt, pom.xml
This PR prepares 0.7.38 release.
=> release 0.7.38

src/main/java/com/treasuredata/client/TDClientException.java, src/main/java/com/treasuredata/client/TDClientSocketException.java, src/main/java/com/treasuredata/client/TDHttpClient.java
=> Catch and retry for most SocketException while requesting to TD API.

CHANGES.txt, pom.xml
@muga Then, ready to release 0.7.39. Can you have a look?
=> release 0.7.39

CHANGES.txt
@muga Sorry on the delay to release... Planning to release v0.7.39 tomorrow. Updating the date in this PR.
Can you have a look?
=> Update the release date of v0.7.39 to 2017-07-27

pom.xml, src/test/java/com/treasuredata/client/TestTDClient.java
- Upgrade `jetty-client` to `9.2.22.v20170606` in attempt to include fix of bug: https://bugs.eclipse.org/bugs/show_bug.cgi?id=441756
=> Upgrade `jetty-client` to 9.2.22.v20170606

src/test/java/com/treasuredata/client/TestTDClient.java
- Update error message: `s/Resource/Presto resource/`
=> Fix unit test: TestTDClient#submitPrestoJobWithInvalidPoolName

CHANGES.txt, pom.xml
This PR prepares 0.7.40 release.
=> release 0.7.40

src/main/java/com/treasuredata/client/TDClient.java
Unlike "POST /v3/table/update-schema/:db/:table", "POST /v3/table/append-schema/:db/:table" can generate alias for column name. So we should do that in not client side but server side.
In this PR, I changed only `appendTableSchema`'s behavior. But I found that `updateTableSchema` seems to send schema in incorrect order too. As I'm not sure how many library depends on `updateTableSchema`'s this behavior, I didn't change it in this PR.
=> Don't send column alias for append-schema API

CHANGES.txt, pom.xml
This PR prepares 0.7.41 release.
=> Release 0.7.41

README.md
- Fix typo on a sample code in `README.md`
=> Fix typo in sample code

src/main/java/com/treasuredata/client/TDClient.java, src/main/java/com/treasuredata/client/TDClientApi.java, src/main/java/com/treasuredata/client/model/TDTableDistribution.java, src/test/java/com/treasuredata/client/TestTDClient.java
Since table distribution information is available at v3 API, added a method for the endpoint.
=> Get table distribution information

CHANGES.txt, pom.xml
=> Release 0.8.10

CHANGES.txt, pom.xml
=> Prepare for release 0.8.11

pom.xml
Fix multiple CVEs related to jackson-databind, by upgrading to the latest version.
=> Fix multiple CVEs related to Jackson

pom.xml
=> Bump checkstyle to 8.31

pom.xml
https://github.com/treasure-data/td-client-java/network/alert/pom.xml/com.fasterxml.jackson.core:jackson-databind/open
=> Fix Jackson vulnerabilities

.github/workflows/javadoc.yml, pom.xml, src/main/java/com/treasuredata/client/BackOffStrategy.java
@yuokada Could you fix the javadoc comments until this CI passes? It's a blocker for releasing 0.9.6.
=> Add javadoc test on CI

.circleci/config.yml, src/test/java/com/treasuredata/client/TestTDClient.java
This PR will:
- Fix updateQueryWithInValidEngineVersion() and updateQueryWithValidEngineVersion() tests
- Use new test account to fix submitJob() test
=> Fix failing integration tests

src/main/java/com/treasuredata/client/TDClient.java, src/main/java/com/treasuredata/client/TDClientApi.java, src/main/java/com/treasuredata/client/model/TDDatabase.java, src/test/java/com/treasuredata/client/TestTDClient.java
- Add the `showDatabase` method
- Add the id field to the TDDatabase class
see: https://api-docs.treasuredata.com/pages/td-api/tag/Databases/#tag/Databases/operation/getDatabaseByName
Close #214
=> Support showDatabase method and etc

pom.xml
=> Bump jackson to address security issues

src/main/java/com/treasuredata/client/TDHttpClient.java, src/main/java/com/treasuredata/client/model/TDJobList.java, src/main/java/com/treasuredata/client/model/TDTable.java, src/test/java/com/treasuredata/client/TestTDClient.java
=> Replace Guava Joiner with JDK8 equivalents

src/main/java/com/treasuredata/client/TDClient.java, src/main/java/com/treasuredata/client/TDHttpClient.java, src/main/java/com/treasuredata/client/TDRequestErrorHandler.java, src/main/java/com/treasuredata/client/model/ObjectMappers.java, src/main/java/com/treasuredata/client/model/TDSavedQueryUpdateRequest.java
Part of #135
Unfortunately, Guava is all-in-one and there is no annotation-only library.
=> Remove Guava VisibleForTesting

src/main/java/com/treasuredata/client/TDClientConfig.java, src/test/java/com/treasuredata/client/TestProxyAccess.java, src/test/java/com/treasuredata/client/TestServerFailures.java, src/test/java/com/treasuredata/client/TestTDClient.java
=> Replace Guava io module with JDK8 equivalents

src/main/java/com/treasuredata/client/TDHttpClient.java
Trivial optimization and best practice
=> Avoid string concatenation in loop

README.md
Fixes
> ![image](https://user-images.githubusercontent.com/127635/221481446-f043dd4e-5bb5-4e74-b183-b0a87a225e47.png)
=> Fixed the broken CircleCI status badge

check-style.xml, src/main/java/com/treasuredata/client/TDClient.java, src/main/java/com/treasuredata/client/TDClientApi.java, src/main/java/com/treasuredata/client/TDHttpClient.java, src/main/java/com/treasuredata/client/model/TDBulkLoadSessionStartRequest.java, src/main/java/com/treasuredata/client/model/TDSavedQuery.java, src/test/java/com/treasuredata/client/model/TestTDColumn.java
- Add the Indentation configuration to check-style.xml
- Reformat java files
Merge this PR after https://github.com/treasure-data/td-client-java/pull/339 is merged
=> Tune check-style.xml

src/main/java/com/treasuredata/client/model/TDSavedQuery.java
Reverts treasure-data/td-client-java#351
=> Revert "Update response for schedule list"
